spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.20.10.9/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
#logging:
 # pattern:
 #   console: "%d - %msg%n"
  #path: /var/log/tomcat/
 # file: /var/log/tomcat/sell/
 # level:
   # com.imooc.sell.LoggerTest: debug
